### PR TITLE
#20 and #35 fetch and display post

### PR DESCRIPTION
**Pull request by I3alan**
- Fetching from S3 is finalized
- Implemented full fetching and display of the latest
  post in DB
- Disply principle is very weak but sufficient for demonstration
  of functionality
- TODO's highlight missing elements required to complete #35

### CODE REVIEW

**Review by jfv-2000 — APPROVED** [review]
Looks good to me

**Review by amqkv — APPROVED** [review]
Good work!

**Review by silentswordxv — APPROVED** [review]
Good work! I'll do make sure to play with the functionalities more soon as well.

**Review by guaj — APPROVED** [review]
Tested, works well

**Review by justpino7 — APPROVED** [review]
Looks good!

**Pull request merged**
