### PR TITLE
Fix login incorrect password bug

### PR DESCRIPTION
**Pull request by jfv-2000**
There was a bug with the login, when  an incorrect password is entered, and then the correct password is entered, the request for the correct password won't proceed. Should be fixed now.

### CODE REVIEW

**Review by amqkv — APPROVED** [review]
Good work!

**Review by I3alan — APPROVED** [review]
Great catch!

**Review by silentswordxv — APPROVED** [review]
Well done, works well.

**Review by guaj — APPROVED** [review]

**Review by justpino7 — APPROVED** [review]
Nicely done!

**Pull request merged**
