### PR TITLE
A login branch refactor

### PR DESCRIPTION
**Pull request by silentswordxv**
The whole project structure changed. Please check it out.

This will be added to the readme, but to run the project (after npm install on both /client and root)
1. cd to root directory
2.  >npm run-script dev

Will probably have to clean up main branch as well depending on what the merge does.

### CODE REVIEW

**Comment by silentswordxv** [comment]
TODO: Edit readme regarding start instructions

**Comment by jfv-2000** [comment]
Looks good, don't forget to associate the task # in the message of the commits @amqkv

**Review by jfv-2000 — APPROVED** [review]
Looks good to me

**Comment by I3alan** [comment]
looks really good!

**Review by I3alan — APPROVED** [review]

**Review by amqkv — APPROVED** [review]
Goodie

**Comment by justpino7** [comment]
Perfect!

**Pull request merged**
