### PR TITLE
#61 implement search feature frontend

### PR DESCRIPTION
**Pull request by guaj**
The front End is completed. There is still an issue with connecting it to the backend. Not sure if its the axios request that have an error or the search route in the backend

### CODE REVIEW

**Review by silentswordxv — APPROVED** [review]
Looks good to me.

**Review by justpino7 — APPROVED** [review]
Good work.

**Review by amqkv — APPROVED** [review]
Looks good!

**Comment by silentswordxv** [comment]
closes #61

**Pull request merged**
