### PR TITLE
#44 Display of followers and following now working

### LINKED ISSUE #44: Display the number of followers/following on the profile of a user (Back-end and Front-End)
Epic #33 

**Description**
On the template of a user profile, show the number of followers and following

-Implement the feature on the back-end
-Modify user template to display followers/following

### PR DESCRIPTION
**Pull request by justpino7**
I did some tests with 2 different users and it seems to work. 
The only moment when it crashed was when I tried to type a non-existing username in the URL. 
Had to reboot the server to be able to revisit the existing user pages and use the following feature again.
Let me know if you have any suggestions on how this could be fixed or if there is something I should modify.

closes #44

### CODE REVIEW

**Review by amqkv — CHANGES_REQUESTED** [review]
I think it would be good if we could find a way to update the follower count right after we follow/unfollow a user instead of having to refresh the page to see the change. I believe this can be achieved if you play around with the states:)

**Comment by justpino7** [comment]
> I think it would be good if we could find a way to update the follower count right after we follow/unfollow a user instead of having to refresh the page to see the change. I believe this can be achieved if you play around with the states:)

It should work now. No need to refresh the page to display the good follower/following count.

**Review by amqkv — APPROVED** [review]

**Comment by amqkv** [comment]
Good work!

**Review by jfv-2000 — APPROVED** [review]
Looks good, nicely done

**Review by silentswordxv — APPROVED** [review]
Works nicely on my end. Nicely done!

**Review by guaj — APPROVED** [review]

**Pull request merged**
