### PR TITLE
#45 backend comments

### LINKED ISSUE #45: Implement the back-end for the comments on the post of a user
Epic #5 
**Description**
Implement the back-end to be able to comment other posts

Notes:
-Create a new database for the comments
-Model of Comments database: PostID, CommentID, author, date, content
-Modify the Post template to contain the CommentID of all comments related to the post
-Have a POST request to add the comment to the Comments database and the CommentID to the Post database

### PR DESCRIPTION
**Pull request by amqkv**
- Comment feature has been implemented
- Turned the create post form into a popup
- Posts are now all fetched from database & displayed on the feed in reverse chronological order

Closes #45

### CODE REVIEW

**Comment by guaj** [comment]
Tested, works great!

**Review by guaj — APPROVED** [review]

**Review by justpino7 — APPROVED** [review]
Good work

**Review by silentswordxv — APPROVED** [review]
Tested. Works great.

**Review by I3alan — APPROVED** [review]
Looks good, great job!

**Pull request merged**
