### PR TITLE
Updated ReadMe file

### PR DESCRIPTION
**Pull request by amqkv**
Updated ReadMe file. Check if you want to add/modify anything

### CODE REVIEW

**Review by jfv-2000 — APPROVED** [review]
Looks good to me

**Review by justpino7 — COMMENTED** [review]
Seems good to me

**Review by silentswordxv — APPROVED** [review]
Good work!

**Comment by silentswordxv** [comment]
@justpino7 you gotta go in `file changed` and hit the `review changes` button to approve it.

**Review by justpino7 — APPROVED** [review]
This should work!

**Review by I3alan — COMMENTED** [review]
Great work!

**Review by I3alan — APPROVED** [review]

**Pull request merged**
