### PR TITLE
#39 Refactoring of components.

### LINKED ISSUE #39: Refactor components
Re-organize the current components into distinct folders and fix any discovered typos. Related to task #17 which currently includes both homepage/main page template and post templates

### PR DESCRIPTION
**Pull request by silentswordxv**
-See title.
-Also added links in current login page to reach homepage without having to manually entering the url. Click on 'Click here' at the bottom :)
-Fixed typos pointed out by @13alan (thanks again!)

closes #39

### CODE REVIEW

**Comment by silentswordxv** [comment]
Forgot to mention, but also added the logo above the post feed + an extra sample post

**Review by amqkv — APPROVED** [review]
Looks good

**Review by I3alan — APPROVED** [review]

**Comment by justpino7** [comment]
This looks better for sure.
I am not familiar on how to deal with merging conflict so just before we merge this branch I would like to know what you guys think about #41 pull request.

**Review by justpino7 — APPROVED** [review]

**Comment by silentswordxv** [comment]
Fixed conflicts.

**Pull request merged**
